### ISSUE TITLE
Typo “packed cell” should be “packed cells”  [two corrections] HeartBEAT manual blood collection processing 4.3.9 Processing Completion

### ISSUE THREAD

**Issue by JLArnold** [nsrr/heartbeat-documentation#27]
https://www.sleepdata.org/datasets/heartbeat/pages/manuals/blood-collection-processing/4-03-09-processing-completion.md

Typo “packed cell” should be “packed cells”  [two corrections] HeartBEAT manual blood collection processing 4.3.9 Processing Completion, typo make word “cell” plural “cells”, “10.0 mL packed cell” should be “10.0 mL packed cells”. Second correction “Urine, packed cell and” should be “Urine, packed cells and”

![image](https://cloud.githubusercontent.com/assets/16805718/12861827/307df16e-cc34-11e5-9598-275534193754.png)

![image](https://cloud.githubusercontent.com/assets/16805718/12861844/4017c80c-cc34-11e5-9723-fe3cdeb63e9e.png)

**Comment by michellereid** [comment]
[a76d7a3](https://github.com/nsrr/heartbeat-documentation/commit/a76d7a35dc36b1f70895575c8118c0a560894a91)
