### ISSUE TITLE
General question about what “HLSE” stands for in the arms of study HeartBEAT manual Schedule of Visits, 1.3 CCI MIMI data mgmt system

### ISSUE THREAD

**Issue by JLArnold** [nsrr/heartbeat-documentation#6]
https://www.sleepdata.org/datasets/heartbeat/pages/manuals/schedule-of-visits/1-03-cci-mimi-data-mgmt-system.md

General question about what “HLSE” stands for in the arms of study HeartBEAT manual Schedule of Visits, 1.3 CCI MIMI data mgmt system,  question should the term “HLSE” be spelled out? There is HLSE-O [I assume O=oxygen therapy] and HLSE-P [I assume P=PAP therapy]

![image](https://cloud.githubusercontent.com/assets/16805718/12852968/8f880670-cbff-11e5-990b-cc189442df70.png)

![image](https://cloud.githubusercontent.com/assets/16805718/12852977/9e114b8e-cbff-11e5-970b-a5b20160de65.png)

**Comment by mrueschman** [comment]
HLSE gets spelled out on the Dataset Introduction page here: https://www.sleepdata.org/datasets/heartbeat/pages/dataset-introduction.md

![image](https://user-images.githubusercontent.com/707167/59701306-57406900-91c3-11e9-95b8-ea1f1c4fc416.png)

Closing outstanding issue.
